version: '3'
services:
  web:
    container_name: napurity-web
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_DATASOURCE_URL=jdbc:mysql://napurity-mysql:3306/napurity?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    build:
      context: .
      dockerfile: web-dockerfile
    working_dir: /web
    ports:
      - 8080:8080
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=prod
  nginx:
    container_name: napurity-nginx
    restart: always
    build:
      context: .
      dockerfile: nginx-dockerfile
    ports:
      - 80:80
    depends_on:
      - web
  mysql:
    container_name: napurity-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: napurity
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp